name: Check compilation
run-name: ${{ github.actor }} is compiling hogc
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main 

jobs:
  compile:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Compilation
        run: make fresh

      - name: Testing compiler
        run: ./hogc test.hog
        working-directory: ./

      - name: Attempting linking
        run: clang test.hog.o -o hogtest -no-pie
        working-directory: ./

      - name: Echo status
        run: echo "Compilation status: ${{ job.status }}"
